name: GitHub Actions Pipeline
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  ADMIN_USER: ${{ secrets.ADMIN_USER }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        modules: [ 'SANITY', 'ADMIN' ]
        browsers: [ 'chromium','firefox' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install playwright browsers
        run: python -m playwright install --with-deps
      - name: Run tests with pytest
        run: pytest -m ${{ matrix.modules }} --tracing=retain-on-failure --browser ${{ matrix.browsers }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ matrix.modules }}-${{ matrix.browsers }}
          path: test-results/
      - name: configure allure action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report-${{ matrix.modules }}-${{ matrix.browsers }}
          allure_history: allure-history-${{ matrix.modules }}-${{ matrix.browsers }}
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history-${{ matrix.modules }}-${{ matrix.browsers }}